### ISSUE TITLE
Aspect Ratio fix not working on Win11

### ISSUE THREAD

**Issue by Spode** [heatray/W3DPatch#1]
Tried the fix on a Win10 VM and it works, but on Win11 the game doesn't render properly with the Aspect Ratio fix enabled. Took some screenshots:
Title screen 1:
![2023-04-04_13-42_3](https://user-images.githubusercontent.com/595105/229782036-551d0cc5-8cfd-4e5c-a6e9-f96eacd39ec2.png)
Title screen 2:
![2023-04-04_13-43](https://user-images.githubusercontent.com/595105/229782049-43021ac9-a04b-4764-95ec-d84cb0b7c763.png)
Menu:
![2023-04-04_13-43_1](https://user-images.githubusercontent.com/595105/229782052-5d308a0b-9493-40d2-9b39-54b4ff18b093.png)

**Comment by heatray** [comment]
Fixed in https://github.com/heatray/W3DPatch/commit/3c8934a075d5ff74a4fe9c74bab6674c65ed3832
Try new version https://github.com/heatray/W3DPatch/releases/tag/v23.4.5

**Comment by Spode** [comment]
That fixed it, thanks! However, with this version the startup video (Team17 logo) and the ingame cutscenes don't render (the audio plays but the screen is black). This is both with and without the aspect ratio fix.

**Comment by heatray** [comment]
Try borderless windowed mode
I have never encountered problems with cutscenes
