### ISSUE TITLE
In-Game videos black during borderless fullscreen

### ISSUE THREAD

**Issue by Sodaro** [heatray/W3DPatch#2]
In-game videos are completely black but have working audio when playing the game at native resolution with /WIN and Borderless enabled (aka "Borderless Fullscreen").
Videos work as expected when disabling borderless or lowering the window resolution.

I was able to reproduce the same issue on two monitors with different resolutions (2560x1440 and 1920x1080).

**Comment by heatray** [comment]
do videos work without a patch and in fullscreen mode?

**Comment by Sodaro** [comment]
The issue appears to be with the base game itself (though it's still present in the patched version). Regular fullscreen causes it as well, at least on Windows 11, but I noticed that if the game isn't focused then the videos render properly.

**Comment by heatray** [comment]
apparently, the problem has been solved by microsoft
I also noticed that Game Bar now works properly on top of opengl fullscreen games
